package tools

import gorm "gorm.io/gorm"

//Generated By github.com/david-yappeter/GormCrudGenerator

//QueryMaker Pagination Query Tools
func QueryMaker(query *gorm.DB, limit *int, page *int, ascending *bool, sortBy *string) {
	sortBy = OrderBy(sortBy, ascending)

	if limit != nil && page != nil && *limit > 0 && *page > 0 {
		offset := (*page - 1) * *limit
		*query = *query.Offset(offset).Limit(*limit)
	}

	if sortBy != nil {
		*query = *query.Order(*sortBy)
	}
}

//OrderBy Order By Generator (ASC,DESC)
func OrderBy(sortBy *string, ascending *bool) *string {
	if sortBy == nil {
		return nil
	}
	if ascending != nil {
		if *ascending {
			sortSyntax := *sortBy + " ASC"
			return &sortSyntax
		}
		sortSyntax := *sortBy + " DESC"
		return &sortSyntax
	}
	return nil
}
